export const FAVORITE = 'FAVORITE';
export const MAIN = 'MAIN';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const REMOVE_ALL_FROM_FAVORITES = 'REMOVE_ALL_FROM_FAVORITES';
export const SET_CURRENT_LENGTH_FILTER_LIST = 'SET_CURRENT_LENGTH_FILTER_LIST';