export const GET_PRICE_DOUBLE_SLIDER = 'GET_PRICE_DOUBLE_SLIDER';
export const FILTER_BY_SEARCH = 'FILTER_BY_SEARCH';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';
export const FILTER_BY_CHEXBOXES = 'FILTER_BY_CHEXBOXES';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const RESET_ALL_FILTERS = 'RESET_ALL_FILTERS';



